[programs.localnet]
forum = "CZNkXA1HaESTi21XtaFmfvGYASHPaVdzdwHFanFLmaek"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/devnet-test1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./tests/programs/metaplex_token_metadata.so"
